_extends: .github
repository:
  name: replace-travis-ci-with-github-actions
  description: utility to remove Travis-CI configuration and enable GitHub Actions
  homepage: 'https://npm.im/@form8ion/replace-travis-ci-with-github-actions'
  private: false
