name: Node.js CI
'on':
  push:
    branches:
      - master
      - alpha
      - beta
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
  PNPM_VERSION: latest-5
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm clean-install
      - run: npm test
      - name: Upload coverage data to Codecov
        run: npm run coverage:report
  verify-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '12.20'
          - 12
          - 14
          - 16
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm clean-install
      - run: npm test
      - name: Upload coverage data to Codecov
        run: npm run coverage:report
  release:
    runs-on: ubuntu-latest
    needs:
      - verify
      - verify-matrix
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm clean-install
      - name: semantic-release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
